### ISSUE TITLE
wrong soil moisture unit measurement

### ISSUE THREAD

**Issue by fidoboulettes** [flatsiedatsie/Mi_Flower_mate_plugin#11]
Hi,
sorry for my poor english.
In first, thanks a lot for this great plugin that simplify the integration of the mi plant in domoticz.

I just want report the wrong unit of measurement used in domoticz for the mi plant. 
The Mi plant indicate a percentage and not a centibar (cb) for the soil humidity.

How (where) to change it in the plugin? I don't find anything in miflora_poller.py elsewhere.

Thanks for your answer

**Comment by flatsiedatsie** [comment]
I'm sorry, I no longer support the Domoticz code. Have you tried the Mozilla WebThings Gateway?

**Comment by fidoboulettes** [comment]
Hi,
what a pity!! 
about Mozilla WTG, i saw it but don't want use it.
Ok, I understand and try to manage it myself.
Thanks for your answer.

**Comment by tonbor** [comment]
> Hi,
> what a pity!!
> about Mozilla WTG, i saw it but don't want use it.
> Ok, I understand and try to manage it myself.
> Thanks for your answer.

Did you find a way to change cb to %
here is de wrong code 
sensorName = sensorBaseName + "Moisture"
					Domoticz.Debug("Creating first sensor, #"+str(sensorNumber))
					Domoticz.Debug("Creating first sensor, name: "+str(sensorName))
					Domoticz.Device(Name=sensorName, Unit=sensorNumber, TypeName="**_Soil Moisture_**", Used=1).Create()   
					Domoticz.Log("Created device: "+Devices[sensorNumber].Name)

**Comment by fidoboulettes** [comment]
Hi Tonbor,
Thanks to you, you help me...
I change TypeName="Soil moisture" into "Percentage" in /domoticz/plugin/Mi Flora.../plugin.py file and re-scan my devices and work well...
Initially, i looked into the poller.py code and find nothing
Thnaks a lot

**Comment by tonbor** [comment]
It is in  the plugin.py code

Op wo 29 apr. 2020 om 14:01 schreef fidoboulettes <notifications@github.com

**Comment by tonbor** [comment]
> I'm sorry, I no longer support the Domoticz code. Have you tried the Mozilla WebThings Gateway?

Only change this 
Domoticz.Device(Name=sensorName, Unit=sensorNumber, TypeName="Soil Moisture", Used=1).Create()
In
Domoticz.Device(Name=sensorName, Unit=sensorNumber, TypeName="Percentage", Used=1).Create()
No big deal
Succes

**Comment by fidoboulettes** [comment]
Hi Tonbor,
why did you use Temperature typename for the soil moisture sensor... It's better to use custom sensor or Humidity No?

**Comment by tonbor** [comment]
> Hi Tonbor,
> why did you use Temperature typename for the soil moisture sensor... It's better to use custom sensor or Humidity No?

You are right, I corrected it to Percentage

**Comment by fidoboulettes** [comment]
Hi Tonbor,
maybe you can help me.
Do you know how to replace the switch in domoticz which launch an measure acquisition by cron in linux?

Thanks

**Comment by tonbor** [comment]
what do you want to do? Did you look her: https://www.domoticz.com/forum/viewtopic.php?t=22083

**Comment by fidoboulettes** [comment]
Hi,
sorry, my english is so poor to explain exactly what i want to do.. :-(

Ok, I want to plan the data acquisition (Temp,Humidity,...) of my Mi flora (1 per hour).
To do that at the moment in domoticz, you most go in switch part, select the switch of Mi plant, and program that... but, my domoticz is in a raspberry and often crash... 
so, after a re-installation of a backup I must re-plan that.

For me, the better thing to do is to make a cron in crontab but I don't know which file (python?) match with the switch (in domoticz).

Thanks for your help

![Capture](https://user-images.githubusercontent.com/12554205/81139667-d4ed9e80-8f66-11ea-8c72-f8488a569516.JPG)

**Comment by tonbor** [comment]
Well you can always start with putty by start hand the plugin.py, see what’s happens. 

 

If it is the correct py file you can put it in crontab starter. (crontab –e).

 

If no luck try the other *.py flowermate files…..

 

Good luck,

 

Tonbor

 

Van: fidoboulettes [mailto:notifications@github.com] 
Verzonden: woensdag 6 mei 2020 6:58
Aan: flatsiedatsie/Mi_Flower_mate_plugin <Mi_Flower_mate_plugin@noreply.github.com>
CC: tonbor <rob.gloudi@gmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [flatsiedatsie/Mi_Flower_mate_plugin] wrong soil moisture unit measurement (#11)

 

Hi,
sorry, my english is so poor to explain exactly what i want to do.. :-(

Ok, I want to plan the data acquisition (Temp,Humidity,...) of my Mi flora (1 per hour).
To do that at the moment in domoticz, you most go in switch part, select the switch of Mi plant, and program that... but, my domoticz is in a raspberry and often crash...
so, after a re-installation of a backup I must re-plan that.

For me, the better thing to do is to make a cron in crontab but I don't know which file (python?) match with the switch (in domoticz).

Thanks for your help

 <https://user-images.githubusercontent.com/12554205/81139667-d4ed9e80-8f66-11ea-8c72-f8488a569516.JPG>

**Comment by flatsiedatsie** [comment]
I've changed the line to user percentage instead.
