### ISSUE TITLE
Conductivity devices created without unit

### ISSUE THREAD

**Issue by BabaIsYou** [flatsiedatsie/Mi_Flower_mate_plugin#12]
Hi,

The conductivity devices are created without any unit, then when someone want to change something (description, icon, name ...) it generates a pop-up in Domoticz asking for a unit before saving modifications. When you add a default unit (ie :  µS/cm that seems to be the unit in apps) this is correct and you can save your changes.

Can it be added at the creation of the device ?

**Comment by flatsiedatsie** [comment]
I'm sorry the answer is: I have no idea. I don't use Domoticz anymore, and this plugin is very old. The code is open source, so feel free to try and fix it.

**Comment by BabaIsYou** [comment]
Hi. That's what i did. Plus some other things and a pull request if you want to add these stuff in the main branch.
