### ISSUE TITLE
Mi_Flower_mate_plugin // Debian 11 / Python3.9

### ISSUE THREAD

**Issue by LiloBzH** [flatsiedatsie/Mi_Flower_mate_plugin#15]
Hi

I tried to upgrade to raspi OS Debian 11 64 bits et mi flora is broken.

i suppose it's because python version is now 3.9 instead of 3.7

someone can confirm et maybe found solution ?

Thanks !

**Comment by flatsiedatsie** [comment]
This plugin is not longer maintained, sorry. Take a look at https://www.candlesmarthome.com.
