### ISSUE TITLE
several bluetooth adaptators

### ISSUE THREAD

**Issue by adrienvia** [flatsiedatsie/Mi_Flower_mate_plugin#6]
Hi, thanks for the plugin, it works very well, (except when it's out of range, and it crashes the plugin entirely...)

I would like to know if it is possible to add an usb bluetooth on the raspberry pi 3, and also use the bluetooth inside the raspberry pi 3, I explain:

I would like to fetch data for several sensors near the raspberry pi with the inside bluetooth adaptator, (that working great for now) but for the sensors out of range, I would like to use another usb bluetooth adaptator on the raspberry pi with a usb cable to reach them.

so I would like to configure the plugin to use both adaptator. (or even configure 2 new hardwares miflora on domoticz, one with each bluetooth adaptator, a simple way to separate the devices out of range from the others)

**Comment by flatsiedatsie** [comment]
Sounds complicated. I would just use the new bluetooth device with all devices.

The best solution would be to create a fix for the crashing if devices are out of range.

**Comment by flatsiedatsie** [comment]
That fix has, in theory, been made.
